language: python
env: PYTHON=python3

matrix:
  include:
    - name: "Python 3.5 on Linux"
      os: linux
      python: 3.5
    - name: "Python 3.6 on Linux"
      os: linux
      python: 3.6
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7
    - name: "Python 3.8 on Linux"
      os: linux
      python: 3.8
    - name: "Python 3 on macOS"
      os: osx
      language: shell
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH PYTHON=python

notifications:
  webhooks:
    - https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

install:
  - ${PYTHON} --version
  - ${PYTHON} -m pip install --upgrade coveralls
  - ${PYTHON} -m pip install --upgrade --editable .[test,md5,bcrypt]
  - ${PYTHON} -m pip list

script:
  - ${PYTHON} setup.py test

after_success:
  - env COVERALLS_PARALLEL=true ${PYTHON} -m coveralls
