name: Generate documentation
on:
  push:
    paths:
    - DOCUMENTATION.md

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Run generator
        run: documentation-generator/run.py
